version: '2'

services:
  # this is our kafka cluster.
  kafka-cluster:
    build: .
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      # ADV_HOST: 192.168.99.100
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
      SAMPLEDATA: 0
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    volumes:
      - /Users/yromaykin/Desktop/GridU/StreamingProcess/StreamProcessing/data:/capstone/data
      - /Users/yromaykin/Desktop/GridU/StreamingProcess/StreamProcessing/docs/kafka-connect:/capstone/scripts
      - /Users/yromaykin/Desktop/GridU/StreamingProcess/StreamProcessing/data/finished:/capstone/data/finished
      - /Users/yromaykin/Desktop/GridU/StreamingProcess/StreamProcessing/data/errors:/capstone/data/errors

  cassandra-1:
    image: cassandra:3.11.4
    ports:
      - "10042:10042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
      - "9042:9042"

  web-console:
    image: apacheignite/web-console-standalone
    ports:
      # Proxy 3001 port from docker container to 3001 port host machine. (HOST_PORT:DOCKER_PORT)
      - "3001:3001"
      - "80:80"
    volumes:
    # External volume for persisting data. (HOST_PATH:CONTAINER_PATH).
    - /Users/yromaykin/Desktop/GridU/StreamingProcess/data/mongo:/data/db
    expose:
      - "8080"
      - "3001"